---
title: "Siamcat Zaura"
format: html
editor: visual
---

```{r}
library(phyloseq)
library(SIAMCAT)
library(stringr)
```

```{r}
phyloZaura <- import_biom("/mnt/STORE1/bighome/cmirzayi/aim3/data/Zaura/taxa.biom")
zaura <- phyloZaura
```

## Determine cases and controls

```{r}
sample_data(zaura)$abx <- 0
sample_data(zaura)$abx[sample_data(zaura)$TreatmentGroup!= "placebo" & sample_data(zaura)$time!= "baseline"] <- 1

sample_data(zaura)$abxfam <- sample_data(zaura)$TreatmentGroup
sample_data(zaura)$abxfam[sample_data(zaura)$time=="baseline"] <- "placebo"

sample_data(zaura)$subject_id <- str_extract(sample_data(zaura)$Description, "[A-Z]+[0-9]*")

subZaura <- subset_samples(zaura, time=="baseline" | time=="week1")
```

```{r}

subZaura <- transform_sample_counts(subZaura, function(OTU) OTU/sum(OTU) )
#subZaura <- filter_taxa(subZaura, function(x) mean(x) > 1e-5, TRUE)
otu_table(subZaura) %>% colSums()
```

```{r}

label.zaura <- create.label(meta=sample_data(subZaura), label="abxfam", case="amox")
sc.obj <- siamcat(feat=otu_table(subZaura), label=label.zaura, meta=sample_data(subZaura))
sc.filt <- filter.features(sc.obj, filter.method = "abundance", cutoff = 0.001)
```

```{r}
sc.assc <- check.associations(
  sc.filt,
  alpha = 0.05,
  mult.corr = "fdr",
  feature.type = "filtered")

association.plot(sc.assc, sort.by = 'fc', 
                panels = c('fc', 'prevalence', 'auroc'))
```

```{r}
sc.conf <- check.confounders(
  sc.filt,
  fn.plot = 'confounder_plots.pdf',
  meta.in = NULL,
  feature.type = 'filtered', verbose = 1
)
```

```{r}
sc.norm <- normalize.features(
  sc.filt,
  norm.method = "pass"
  )
```

```{r}
sc.split <-  create.data.split(
  sc.norm,
  num.folds = 6,
  num.resample = 10,
  inseparable = "subject_id"
)

```

```{r}
sc.mod <- train.model(
  sc.split,
  method = "randomForest"
)

sc.pred <- make.predictions(sc.mod)

pred_matrix <- pred_matrix(sc.pred)
```

```{r}
sc.eval <- evaluate.predictions(sc.pred)

model.evaluation.plot(sc.eval)
```

```{r}
model.interpretation.plot(
sc.eval,
fn.plot = 'zaura_siamcat.pdf',
consens.thres = 0.01,
limits = c(-3, 3),
heatmap.type = 'zscore'
) 
```

## Exploratory data analysis

Subset to post exposure only then run PCoA

```{r}

sample_data(subZaura)$Condition <- sample_data(subZaura)$abxfam
sample_data(subZaura)$Condition[sample_data(subZaura)$Condition=="amox"] <- "penicillins"
sample_data(subZaura)$Condition[sample_data(subZaura)$Condition=="cipro"] <- "quinolones"
sample_data(subZaura)$Condition[sample_data(subZaura)$Condition=="clinda"] <- "lincomycins"
sample_data(subZaura)$Condition[sample_data(subZaura)$Condition=="minoc"] <- "tetracyclines"
sample_data(subZaura)$Condition[sample_data(subZaura)$time=="baseline"] <- "baseline"
sample_data(subZaura)$abx <- as.factor(sample_data(subZaura)$abx)
zauraord <- ordinate(subZaura, method="PCoA", "bray")
plot_ordination(subZaura, zauraord, type="samples", color="Condition", label = "subject_id", shape="Condition")+scale_color_manual(values=c("black", "orange", "blue", "black", "green", "red"))

```

```{r}
raydist <- phyloseq::distance(subZaura, method="bray") %>% as.matrix() %>% as.data.frame()
raydist$sample_id <- colnames(raydist)
sampray <- data.frame(sample_data(subZaura))
sampray$sample_id <- rownames(sampray)

library(tidyr)
step1 <- dplyr::inner_join(sampray, raydist) %>% select(subject_id |sample_id |time | abxfam| starts_with("SRR")) %>% pivot_longer(cols=starts_with("SRR")) %>% mutate(sample1 = sample_id, sample2=name)

  step2 <- sampray %>% select(sample2=sample_id, sub2=subject_id, time2=time)

step3 <- dplyr::inner_join(step1, step2) %>% filter(subject_id==sub2, time != time2) %>%  group_by(subject_id) %>% summarize(value=first(value), condition=last(abxfam))

rayamox<- step3 %>% filter(condition=="amox") 
rayplacebo <- step3 %>% filter(condition=="placebo")
rayminoc <- step3 %>% filter(condition=="minoc")
rayclinda <- step3 %>% filter(condition=="clinda")
raycipro <- step3 %>% filter(condition=="cipro")

library(ggthemes)
ggplot(rayamox, aes(x=value, color= "Penicillins", ..scaled..))+geom_density()+geom_density(data=rayplacebo, aes(color="Placebo")) +
  geom_density(data=rayminoc, aes(color="Tetracyclines")) +
  geom_density(data=rayclinda, aes(color="Lincomycins")) +
  geom_density(data=raycipro, aes(color="Quinolones")) +
   labs(color=NULL, x="Bray-Curtis dissimilarity between t0 and t7", y="Density Estimate")+
   theme(legend.position = c(0, 1),legend.justification = c(0, 1), legend.title = element_blank())+
  scale_color_manual(values = c("red","green", "blue", "purple", "orange"))+theme_clean()
```

PERMANOVA

```{r}
library(vegan)
metadata <- as(sample_data(subZaura), "data.frame")

adonis2(distance(subZaura, method="bray") ~ abxfam + subject_id,
       data = metadata)
```
